import { makeStyles } from '@mui/styles'
import { Theme } from 'theme'

const useStyles = makeStyles((theme: Theme) => ({
  container: {
    position: 'relative',
    maxWidth: '240px',
    boxSizing: 'border-box',
    margin: '5px',
    paddingTop: '1rem',
    color: ({ primaryColor }: Theme) => primaryColor,
    '& label': {
      position: 'absolute',
      top: '1.5rem',
      left: '0',
      marginLeft: '30px',
      fontWeight: 'normal',
      zIndex: '1',
      cursor: 'text',
      lineHeight: '1rem',
    },
    '& input': {
      WebkitAppearance: 'none',
      MozAppearance: 'none',
      appearance: 'none',
      border: '0 none',
      margin: 0,
      background: ({ primaryBackground }: Theme) => primaryBackground,
      fontSize: '13px',
      position: 'relative',
      WebkitTransition: 'box-shadow 200ms ease-out,opacity 200ms ease-out',
      MozTransition: 'box-shadow 200ms ease-out,opacity 200ms ease-out',
      transition: 'box-shadow 200ms ease-out,opacity 200ms ease-out',
      boxShadow: ({ smallInsetShadow }: Theme) => smallInsetShadow,
      borderRadius: '4px',
      lineHeight: '20px',
      display: 'inline',
      textAlign: 'left',
      minHeight: '32px',
      width: '100%',
      paddingLeft: '30px',
      paddingRight: '30px',
      boxSizing: 'border-box',
      color: 'inherit',
      '&:focus ~ label, &:not([value=""]) ~ label': {
        top: '0px',
        marginLeft: '5px',
        fontSize: '13px',
        fontWeight: 700,
      },
    },
  },
  preview: {
    position: 'absolute',
    display: 'block',
    top: '1.25rem',
    left: '0.1875rem',
    width: '1rem',
    height: '1rem',
    boxShadow: ({ smallInsetShadow }: Theme) => smallInsetShadow,
    cursor: 'pointer',
    borderRadius: '4px',
    margin: '4px',
    background: 'white',
    overflow: 'hidden',
    '& svg': {
      display: 'block',
    },
    zIndex: 1,
  },
  color: {
    width: '1rem',
    height: '1rem',
    display: 'block',
    position: 'absolute',
    top: 0,
    borderRadius: '4px',
    boxShadow: ({ smallInsetShadow }: Theme) => smallInsetShadow,
  },
  selectorWrapper: {
    top: '100%',
    left: '0px',
    position: 'absolute',
    display: 'inline-block',
    zIndex: 999,
    background: ({ primaryBackground }: Theme) => primaryBackground,
    filter:
      'drop-shadow(0px 5px 5px rgba(0,0,0,0.05)) drop-shadow(0 1px 3px rgba(0,0,0,0.1))',
    WebkitFilter:
      'drop-shadow(0px 5px 5px rgba(0,0,0,0.05)) drop-shadow(0 1px 3px rgba(0,0,0,0.1))',
    borderRadius: '8px',
    fontSize: '12px',
    marginTop: '5px',
    height: '210px',
  },
  indicator: {
    position: 'absolute',
    top: '-8px',
    left: '7px',
    borderStyle: 'solid',
    borderBottomWidth: '8px',
    borderTopWidth: '0px',
    borderRightWidth: '8px',
    borderLeftWidth: '8px',
    borderBottomColor: ({ primaryBackground }: Theme) => primaryBackground,
    borderTopColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  selector: {
    width: '200px',
    margin: '5px',
    boxSizing: 'border-box',
    '& .react-colorful__pointer': {
      backgroundColor: ({ primaryBackground }: Theme) => primaryBackground,
      borderColor: ({ primaryBackground }: Theme) => primaryBackground,
    },
  },
  svg: {
    shapeRendering: 'inherit',
    webkitTransform: 'translate3d(0,0,0)',
    msTransform: 'translate3d(0,0,0)',
    transform: 'translate3d(0,0,0)',
    display: 'block',
    position: 'absolute',
    zIndex: 1,
    top: '22px',
    right: '7px',
    width: '20px',
    height: '20px',
    padding: '4px',
    boxSizing: 'border-box',
    cursor: 'pointer',
    '& path': {
      fill: 'currentcolor',
    },
  },
}))

export default useStyles
